<?php
	session_start();
	@$username=$_SESSION["username"];
	$_SESSION=array();
	session_destroy();
	setcookie("username","",time()-3600);
	setcookie("userid","",time()-3600);
	setcookie("islogin","",time()-3600);
	header("Location:login.php");
?>